language: java
java:
  - 1.8.0_231
install: true
script:
  - mvn clean install

branches:
  only:
    - master
deploy:
  provider: heroku
  app: herokutask2
  api_key:
    secure: 828d3754-6c8a-40f4-b93d-48438849286a
